spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: 校园选课系统

app:
  name: 校园选课系统
  version: v1.2.0

logging:
  level:
    com.zjgsu.obl.course.Course: INFO
    org.hibernate.SQL: DEBUG